Add some tech arch principles
ministryofjustice/cloud-platform pull request #2359
Opened 2020-09-23 11:56 UTC by davidread

I've tried to synthesize some of the key tech principles I've heard recently from @digitalronin and @SteveMarshall - very happy to receive feedback.

I think these sit next to the [product description](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/about-the-cloud-platform.html#about-the-cloud-platform), but are more tech focused. 

Maybe there's a better place to put these, as this tech arch doc is otherwise pretty focussed on what has actually been built. But I feel all this material is written by a tech arch, both for themself to structure their thoughts, but also to record and communicate for the CP team as well as service teams. So maybe it does fit here.

2020-09-23 13:19 UTC, digitalronin approved these changes
I like it. I'm sure we'll iterate and add stuff as we go. I think this is a great start.

2020-09-24 10:09 UTC, SteveMarshall approved these changes
This is 🔥, thanks @davidread! A few minor comments, but I'm happy for this to go if you'd like to address those another way (or leave them as-is for now);.

2020-09-24 10:09 UTC, SteveMarshall commented on docs/Architecture-Offical.md
> +We embed ops tools and best practices into a platform, to benefit all service teams.
… and use the platform to increase the service teams' ability to operate their services over time, and increase the MOJ's level of engineering quality too? Or something? Essentially, I want the Cloud Platform (and other platforms we offer) to be driving their users to get better at everything, all the time, without it feeling like a chore.

2020-09-24 10:09 UTC, SteveMarshall commented on docs/Architecture-Offical.md
> +### Clusters are cattle
This might be better as `Infrastructure is cattle`, because we want the clusters to be cattle, but also the service-specific stuff to be, too? Or something like that.

2020-09-24 10:09 UTC, SteveMarshall commented on docs/Architecture-Offical.md
> +As hosting technology and ideas change and improve, we will relentlessly reinvent all aspects of the platform, to serve user needs better. We shall not be afraid to replace the whole platform, if tha
✊

2020-09-24 17:12 UTC, davidread commented
Thanks for the feedback! I've built on all that's been said, so let me know if this is all good.

2020-09-25 08:14 UTC, digitalronin requested changes
Looks great. Just one small typo.

2020-09-25 08:14 UTC, digitalronin commented on docs/Architecture-Offical.md
> +The process starts with the user pushing some code to GitHub. The pipeline automatically detects the new change and then processes it. This ultimately results in a resource change in Kubernetes/AWS.
Typo
> and architecture the enables it
should be "and the architecture that enables it"

2020-09-25 08:26 UTC, SteveMarshall commented on docs/Architecture-Offical.md
> +Clusters are cattle. We can't have one cluster, vulnerable to a fault, YOLO changes and upgrades. Clusters need to be disposible. Replacement is automatic and seamless.
> YOLO changes

😂

2020-09-25 08:26 UTC, SteveMarshall approved these changes
🔥 

Thanks @davidread!

2020-09-25 08:32 UTC, davidread commented on docs/Architecture-Offical.md
> +Clusters are cattle. We can't have one cluster, vulnerable to a fault, YOLO changes and upgrades. Clusters need to be disposible. Replacement is automatic and seamless.
on reflection, that oversteps the mark...

2020-09-25 08:33 UTC, SteveMarshall commented on docs/Architecture-Offical.md
> +Clusters are cattle. We can't have one cluster, vulnerable to a fault, YOLO changes and upgrades. Clusters need to be disposible. Replacement is automatic and seamless.
I like it!

2020-09-25 08:38 UTC, digitalronin approved these changes

2020-09-25 08:39 UTC, merged