Add draft of EKS ADR
ministryofjustice/cloud-platform pull request #2931
Opened 2021-05-27 17:08 UTC by davidread

(The deleted text was mistakenly copied from another ADR)

2021-05-28 09:13 UTC, razvan-moj submitted a review, later dismissed

2021-06-08 10:19 UTC, razvan-moj requested changes

2021-06-08 10:19 UTC, razvan-moj commented on architecture-decision-record/022-EKS.md
> +We've long used Kuberos for issuing kubecfg credentials to users. The [original version of Kuberos](https://github.com/negz/kuberos) is unmaintained, but it's pretty simple, so we are updating the de
thanks to @poornima-krishnasamy we can use the past tense here :)

2021-06-08 10:19 UTC, razvan-moj commented on architecture-decision-record/022-EKS.md
> +**Chosen:** AWS Systems Manager, installed as daemonset; no bastion nodes
We don't have a story for this, so might get forgotten

2021-06-08 10:19 UTC, razvan-moj commented on architecture-decision-record/022-EKS.md
> +**Chosen:** Block access to instance metadata's node role
I think we already made a choice here: "using kube2iam"

2021-06-08 10:19 UTC, razvan-moj commented on architecture-decision-record/023-Logging.md
> +
another bullet point: fluent+AWS ES combo has no flexibility to parse/define the JSON structure of logs, so all our teams right now have to contend with grabbing the contents of a single `log` field and parsing it outside ES

2021-06-11 15:31 UTC, davidread commented on architecture-decision-record/022-EKS.md
> +* IAM auth has the benefit of immediately revoking access. Maybe we could use federated login with GitHub? (But would that give only temporary kubecfg?) Or sync the GitHub team info to IAM?
I can see the reasoning for this, keeping this document clean and 'final'. On the other hand I like to draw together related things, even if they are uncertain and subject to change. It seems a bit early to create tickets for these things because it might be months before we have a reason to work on them.

2021-06-11 15:41 UTC, davidread commented on architecture-decision-record/022-EKS.md
> +**Chosen:** AWS Systems Manager, installed as daemonset; no bastion nodes
Added a ticket: https://github.com/ministryofjustice/cloud-platform/issues/2962 and linked to it in this ADR

2021-06-11 15:42 UTC, davidread commented on architecture-decision-record/022-EKS.md
> +**Chosen:** Block access to instance metadata's node role
We can add implementation decision afterwards - not essential for this ADR I think

2021-06-11 15:43 UTC, davidread commented on architecture-decision-record/023-Logging.md
> +
That's a really good point - thanks for expressing it here - added.

2021-06-11 15:47 UTC, razvan-moj approved these changes

2021-06-11 15:47 UTC, merged