Update doc for live cluster
ministryofjustice/cloud-platform pull request #3721
Opened 2022-04-20 17:19 UTC by poornima-krishnasamy

2022-04-21 09:18 UTC, razvan-moj commented on runbooks/source/manually-apply-namespace.html.md.erb
> +export TF_VAR_cluster_state_key="cloud-platform/live/terraform.tfstate"
I *think* the cluster state key is unchanged?

2022-04-21 09:19 UTC, razvan-moj requested changes
check state location pls

2022-04-21 11:31 UTC, poornima-krishnasamy commented on runbooks/source/manually-apply-namespace.html.md.erb
> +export TF_VAR_cluster_state_key="cloud-platform/live/terraform.tfstate"
That is the cluster state we set in pipeline https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/environments-live.yaml#L158. The environments folder is what we havent changed and that remains `live-1.cloud...` when we do the terraform init.

2022-04-22 12:23 UTC, razvan-moj approved these changes

2022-04-22 14:00 UTC, merged